### ISSUE TITLE
No face detected error and unable to login or sign up

### ISSUE THREAD

**Issue by parkjuwon-ai** [srockstech/face-pass#1]
Hello,

I am facing an issue with the face_pass application. When I try to use the app, I encounter the following problems:

1. "No face detected" message appears even when the camera is pointed at a face.
2. Unable to login or sign up.

Here are the details of my environment:
- Device: Samsung Galaxy S10
- Android Version: 12
- Flutter Version: 3.22.2
- Gradle Version: 7.0.2

Steps to reproduce the issue:
1. Clone the repository.
2. Open the project in Android Studio.
3. Run `flutter pub get` to install dependencies.
4. Run the app on a device.
5. Attempt to login or sign up.

I have followed all the setup instructions provided in the repository. However, the above issues persist.

Could you please help me resolve these issues?

Thank you.

**Comment by srockstech** [comment]
@parkjuwon-ai Thank you for raising this issue. This issue has been resolved now. Hence closing this one. If you are willing to contribute to the project, you can pull the latest changes and raise new issues for any bugs or new features you would like to add, I will assign those to you.
